name: Full CI/CD pipeline

on:
  push:
    branches: [main]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Set short git commit SHA
        id: vars
        run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV # or use 'echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT' for a step output

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: building  and pushing docker image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.ECR_REPO }}:${{ env.COMMIT_SHORT_SHA }} \
          -t ${{secrets.ECR_REPO }}:latest \
          --push .
